### ISSUE TITLE
Move blog title out of post avoid H1 SEO conflict

### ISSUE THREAD

**Issue by fongjason** [artofmarketingscience/artofmarketingscience.github.io#23]
Move site title out of blog posts and pages . Currently conflicting H1 tags for SEO. Move `Art of Marketing Data Science` up to banner bar

<img width="1171" alt="Screen Shot 2020-12-02 at 2 37 06 PM" src="https://user-images.githubusercontent.com/20663984/100922568-0ce0a400-34ac-11eb-93b0-b87943249a68.png">

**Comment by fongjason** [comment]
Likely removing 

```
<!-- Site Title
================================================== -->
<div class="mainheading">
    <h1 class="sitetitle">{{ site.name }}</h1>
    <p class="lead">
         {{ site.description }}
    </p>
</div>
```

From the default.html

**Comment by fongmanfong** [comment]
Done
